### ISSUE TITLE
Cannot run examples

### ISSUE THREAD

**Issue by omarjaved83** [runtimeverification/javamop#214]
I am trying to run an example of CFG. But when I run I get the following error. Java is working, so is ajc.
bu when I run javamop HasNext.mop. I get the following error
Exception in thread "main" java.lang.NoClassDefFoundError: com/runtimeverification/rvmonitor/core/parser/RVParser
	at javamop.parser.JavaParserAdapter.parse(JavaParserAdapter.java:156)
	at javamop.parser.SpecExtractor.parse(SpecExtractor.java:30)
	at javamop.JavaMOPMain.processSpecFile(JavaMOPMain.java:117)
	at javamop.JavaMOPMain.process(JavaMOPMain.java:326)
	at javamop.JavaMOPMain.process(JavaMOPMain.java:370)
	at javamop.JavaMOPMain.main(JavaMOPMain.java:406)
Caused by: java.lang.ClassNotFoundException: com.runtimeverification.rvmonitor.core.parser.RVParser
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more

Which jar file do I have to include in my class path

**Comment by xiaohe27** [comment]
Two more jars are needed in your case: the rv-monitor.jar and rv-monitor-rt.jar

**Comment by omarjaved83** [comment]
Thank you, the installer also had the same instructions which I found out later. But thank you.
